#!/bin/bash

#
# CONFIG
#

CONTAINER=terminus-server
REPOSITORY=terminusdb/terminus-server
TAG=latest

SERVER=localhost
PORT=6363:6363
PASS=root

#
# functions
#

usage () {
  printf "\
USAGE:
  terminus-container [COMMAND]

  pull      pull from dockerhub
  create    create container
  rm        remove container
  start     start container
  stop      stop container
  restart   restart container\n"
}

#
# PROCESS ARGS
#

printf "\n"

if [ ! -z "$1" ]; then
  case "$1" in
    "pull")
    sudo docker pull $REPOSITORY:$TAG
    ;;
    "create")
    sudo docker create --name $CONTAINER \
      -p $PORT -e SERVER_NAME=$SERVER -e \
      DB_PASS=$PASS -t \
      $REPOSITORY:$TAG \
      && printf "terminus-server container created\n" \
      || printf "\nHas the container already been created?\n"
    ;;
    "rm")
    sudo docker rm $CONTAINER > /dev/null \
      && printf "terminus-server container removed\n" \
      || printf "\nHas the container been created?\n"
    ;;
    "start")
    sudo docker start $CONTAINER > /dev/null \
      && printf "terminus-server container started\n" \
      || printf "\nHas the container been created?\n"
    ;;
    "stop")
    sudo docker stop $CONTAINER > /dev/null \
      && printf "terminus-server container stopped\n" \
      || printf "\nHas the container been created?\n"
    ;;
    "restart")
    sudo docker stop $CONTAINER > /dev/null \
      && printf "terminus-server container restarted\n" \
      || printf "\nHas the container been created?\n"
    ;;
    *)
    printf "invalid command\n"
    ;;
  esac
else
  usage
fi

printf "\n"

# vim: set filetype=sh :
